version: "3"

services:
  #cache için redis kullanılıyor
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

#Log kayıtları için mongodb kullanılıyor
  mongodb:
    image: mongo:latest
    container_name: bookshop-mongodb
    ports:
      - "27017:27017"
